### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by itsdn** [xmpp4r/xmpp4r#40]

**Comment by blanchma** [comment]
+1 there is no one line of good documentation, or if it is, is not clear where.

**Comment by badboy** [comment]
xmpp4r uses inline documentation, which can be nicely formatted and extracted using the popular rdoc. Simply run `rake rerdoc` locally and open `rdoc/index.html` or even easier go to <http://www.rubydoc.info/gems/xmpp4r/frames>.

Indeed one of these hosted documentations should be linked from the README and the GitHub repo

**Comment by qbasicer** [comment]
Some example would be helpful too, such as how to use the XDelay class

**Comment by itsdan** [comment]
You cannot actually call that documentation if there's no explanation of how to generate one. Inline documentation will never explain the basic principles of the gem. Installation process isn't covered, examples are hard to read, they aren't structured in any reasonable way and they aren't self-explanatory.

This project is abandoned and I wouldn't recommend this gem as a solution to your projects unless you want to experience misunderstanding and frustration.

**Comment by mistergibson** [comment]
I found this useful: http://www.rubydoc.info/gems/xmpp4r/0.5.6/Jabber/Client
