### ISSUE TITLE
n00b Question: how do I trap for incoming file transfer requests, and responses to my file transfer offers?

### ISSUE THREAD

**Issue by mistergibson** [xmpp4r/xmpp4r#55]
I've looked at the source code - and it all seems to make sense. However, the event that triggers it all remains a mystery to me. I use add_subscription_request_callback on the @roster  to process incoming chat invitations - is the process for file transfers the same?

Thanks in advance.

G. Gibson

**Comment by mistergibson** [comment]
Nevermind - figured it out.

**Comment by coderhs** [comment]
@mistergibson Do share how you did it? Would be useful for the next person who might come along and see this issue.

**Comment by rosid86** [comment]
#55
