### ISSUE TITLE
List of supported XEPs?

### ISSUE THREAD

**Issue by sjehuda** [xmpp4r/xmpp4r#66]
Greetings!

Is there a list of supported XEPs?

I want to know what is the scope of support in XEP-0060: Publish-Subscribe.

Thank you

**Comment by astro** [comment]
There is no such list. Plenty of older XEPs are supported but probably not in their latest version given the age of this library.

I added support for PubSub 18 years ago. See:
- https://github.com/xmpp4r/xmpp4r/tree/master/lib/xmpp4r/pubsub
- https://github.com/xmpp4r/xmpp4r/blob/master/data/doc/xmpp4r/examples/advanced/pep-aggregator/pep-aggregator.rb

**Comment by sjehuda** [comment]
Thank you!

I have referred @jekyll and @octopress to this library for adding PubSub support.
